export enum AreaExecutora {
  INFRAESTRUTURA = "INFRAESTRUTURA",
  DESENVOLVIMENTO = "DESENVOLVIMENTO",
  BUSINESS_INTELLIGENCE = "BUSINESS_INTELLIGENCE",
  ALOCACAO_DE_RECURSOS = "ALOCACAO_DE_RECURSOS",
  HUNTING_DE_RECURSOS = "HUNTING_DE_RECURSOS",
}
